import type { NextPage } from "next";
import Head from "next/head";
import { TabCards } from "@/src/components/TabCards";
import { tabsData } from "@/src/components/TabCards/TabsData";

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <TabCards title="Technologies, tools &amp; more" tabs={tabsData} />
        </>
    );
};

export default Home;
