import type { NextPage } from 'next'
import Head from 'next/head'
import { TabCards } from '@/src/components/TabCards'
import { tabs } from '@/src/components/TabCards/TabCardsTypes'

const Home: NextPage = () => {
  const tabs: tabs[] = [
    {
      icon: "",
      label: "Tech",
      cards: [
        {
          logo: "",
          title: "HTML5",
          desc: "Markup language for structuring web pages"
        }
      ]
    }
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TabCards title="Technologies, tools &amp; more" tabs={tabs} />
    </>
  )
}

export default Home
